name: dartora
description: A large utility package.
version: 0.1.0
homepage: https://officer-erik-1k-88.github.io/dartora/
repository: https://github.com/Officer-Erik-1K-88/dartora
issue_tracker: https://github.com/Officer-Erik-1K-88/dartora/issues

topics:
  - utilities
  - utility
  - utils
  - dart

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
